CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_miles_flown INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_customer_status CHECK (status IN ('GOLD', 'SILVER', 'NONE'))
);

CREATE TABLE flights (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(50) NOT NULL UNIQUE,
    aircraft VARCHAR(255) NOT NULL,
    total_aircraft_seats INTEGER NOT NULL,
    mileage INTEGER NOT NULL
);

CREATE TABLE flight_bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    flight_id INTEGER NOT NULL,
    CONSTRAINT uk_flight_booking_customer_flight UNIQUE (customer_id, flight_id),
    CONSTRAINT fk_flight_booking_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_flight_booking_flight FOREIGN KEY (flight_id) REFERENCES flights(id)
);
