CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    customer_status VARCHAR(20) NOT NULL,
    total_customer_mileage INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_customer_status CHECK (customer_status IN ('GOLD', 'SILVER', 'NONE'))
);

CREATE TABLE flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(50) NOT NULL UNIQUE,
    aircraft VARCHAR(255) NOT NULL,
    total_aircraft_seats INTEGER NOT NULL,
    flight_mileage INTEGER NOT NULL
);

CREATE TABLE flight_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    flight_id BIGINT NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_flight_booking_customer_flight UNIQUE (customer_id, flight_id),
    CONSTRAINT fk_flight_booking_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_flight_booking_flight FOREIGN KEY (flight_id) REFERENCES flights(id)
);
